<?php

namespace App\Concerns;

use Illuminate\Support\Carbon;

/**
 * Locale-aware date wording for the bazaar. The site's Arabic strings are
 * hand-written rather than generated by ext-intl, so weekday and month names
 * are kept here in one place and shared by the models that print dates.
 */
trait ArabicDateNames
{
    private static function arabicWeekdays(): array
    {
        return [
            'Saturday' => 'السبت', 'Sunday' => 'الأحد', 'Monday' => 'الاثنين',
            'Tuesday' => 'الثلاثاء', 'Wednesday' => 'الأربعاء',
            'Thursday' => 'الخميس', 'Friday' => 'الجمعة',
        ];
    }

    private static function arabicMonths(): array
    {
        return [
            1 => 'يناير', 2 => 'فبراير', 3 => 'مارس', 4 => 'أبريل',
            5 => 'مايو', 6 => 'يونيو', 7 => 'يوليو', 8 => 'أغسطس',
            9 => 'سبتمبر', 10 => 'أكتوبر', 11 => 'نوفمبر', 12 => 'ديسمبر',
        ];
    }

    protected static function arabicWeekday(Carbon $date): string
    {
        return self::arabicWeekdays()[$date->format('l')] ?? $date->format('l');
    }

    protected static function arabicMonth(Carbon $date): string
    {
        return self::arabicMonths()[(int) $date->format('n')] ?? '';
    }

    /** "الخميس 23 يوليو" */
    protected static function arabicDate(Carbon $date): string
    {
        return self::arabicWeekday($date).' '.$date->format('j').' '.self::arabicMonth($date);
    }
}
